---
Name: silverstripe-sections
After:
  - 'framework/*'
  - 'cms/*'
---
Page:
  extensions:
    - SectionPageExtension
Injector:
  GridField:
    class: RowExtraClassesGridField
LeftAndMain:
  extra_requirements_css:
    - 'sections/css/CMSMain.GridField.css'
  extra_requirements_javascript:
    - 'sections/js/CMSMain.SectionForm.js'
